### PR TITLE
Update 03-15-07_sca-treasurer-wai-role.md

### PR DESCRIPTION
**Pull request by sca-pastpresident**
New section added to Handbook based on the 2020 Western Archives Institute revised Handbook as approved by the Board at the January 2021 Board meeting; revisions made as requested by the Board at the May 2022 Board meeting.

### CODE REVIEW

**Comment by sca-secretary** [comment]
@calarchivists/sca-board -- As this is a new section in the SCA Handbook, all SCA Board members should review this new section. Thanks!

**Review by sca-secretary — COMMENTED** [review]
@sca-pastpresident I'm wondering if an intro/context-setting sentence could help frame the purpose of this page.

Are these WAI's responsibilities? Or are these the SCA Treasurer's responsibilities? Thanks!

**Review by SCA-VP — APPROVED** [review]

**Comment by sca-president** [comment]
> 

This is paraphrased from the WAI Handbook, section 2-1: _The SCA Treasurer is a member of the Western Archives Institute (WAI) Management Committee. The WAI Management Committee is an SCA standing committee and composed of eight (8) members who supervise the administration of WAI.

**Comment by sca-pastpresident** [comment]
How about under the "General" heading we write "See WAI Handbook section 2-7" instead of "See SCA Handbook, section 2-5?" Although WAI Handbook section 2-7 is the exact same thing as is written here, and has a note that points back to the SCA Handbook section 2-5 so it's rather circular. But maybe directing back to the WAI Handbook makes more sense than directing to the SCA Handbook for the Treasurer's WAI role.

**Comment by sca-pastpresident** [comment]
@sca-secretary -- Yes, I like it. Thank you, Christine!

Leilani

**Review by sca-secretary — APPROVED** [review]

**Pull request merged**
