### PR TITLE
Update 02-08_directors-at-large.md

### PR DESCRIPTION
**Pull request by katedundon**
Changed "Director" to "Member" at large. This change was decided in the November 2022 SCA Board meeting.

### CODE REVIEW

**Comment by sca-president** [comment]
Accept

**Review by sca-membership — APPROVED** [review]

**Comment by sca-pastpresident** [comment]
Not sure that we can change the wording in this section from "director/director-at-large" to "member/member-at-large" since the By-Laws refer to these members of the Board as "Directors." See section IV "OFFICERS & GOVERNMENT," pages 2-4.

**Comment by sca-secretary** [comment]
See revisions proposed in #16 -- also will impact #13

**Comment by sca-secretary** [comment]
Closing this pull request without merging. Discussed during the April 2023 Board meeting that according to the Bylaws, the official title is "Directors-at-Large."

**Pull request closed without merging**
