### PR TITLE
Adding new membership form sample

### PR DESCRIPTION
**Pull request by sca-membership**
Removed mailing address, added language to email Membership Director for current mailing address

### CODE REVIEW

**Comment by sca-secretary** [comment]
@calarchivists/sca-board requesting review of the updated sample membership form. To view the updated PDF file, please go to the "Files changed" tab > click the three dots icon (...) on the right side > on the dropdown, choose "View file"

Please comment here once you've reviewed the file. Thanks!

**Comment by sca-membership** [comment]
Please make sure this updated PDF is linked to in the Handbook section 2-7-6

**Review by SCA-VP — APPROVED** [review]

**Review by SCA-VP — APPROVED** [review]

**Comment by sca-secretary** [comment]
Merged this in because I thought it was just the membership form. However, this PR also includes revisions to 03-11, which may need Board review.

**Comment by sca-pastpresident** [comment]
We need to discuss the donation option "Advancing Equity Fund" with Alex, since I think this is misrepresented and there isn't actually a fund for this award/scholarship

**Pull request merged**
